export const phrases:string[] = [
  "el veloz murcielago hindu comia feliz cardillo y escabeche",
  "programar es un arte que requiere mucha paciencia y practica",
  "la musica amansa a las fieras en el bosque profundo",
  "un pequeño paso para el hombre pero un gran salto para la humanidad",
  "el codigo limpio es como una buena receta de cocina",
  "las nubes grises tambien forman parte del paisaje diario",
  "el exito consiste en ir de fracaso en fracaso sin desanimarse",
  "la logica te llevara de un punto a otro con seguridad",
  "aprender algo nuevo cada dia es un habito muy saludable",
  "el cafe caliente ayuda a despertar los sentidos por la mañana",
  "las estrellas brillan con fuerza en las noches despejadas",
  "un amigo es aquel que llega cuando el resto se va",
  "la vida es lo que pasa mientras haces otros planes",
  "la curiosidad es el motor del aprendizaje continuo",
  "el sol sale para todos cada mañana sin falta",
  "una imagen vale mas que mil palabras bien dichas",
  "el conocimiento no ocupa lugar pero pesa en la mente",
  "la calma es la llave de muchas puertas cerradas",
  "caminar por el bosque ayuda a despejar la cabeza",
  "el teclado suena como una lluvia fina de letras",
  "cada linea de codigo es una oportunidad de mejorar",
  "los errores son lecciones disfrazadas de problemas",
  "la montaña parece alta hasta que empiezas a subir",
  "el agua del mar esta fria pero el sol calienta la arena",
  "beber mucha agua es bueno para la salud del cuerpo",
  "la lectura abre puertas a mundos desconocidos y magicos",
  "el tiempo vuela cuando te diviertes con amigos",
  "una sonrisa puede cambiar el dia de cualquier persona",
  "la paciencia es una virtud que pocos logran dominar",
  "el gato duerme placidamente sobre el sofa verde",
  "las flores crecen con la lluvia de la primavera",
  "programar en la noche tiene un toque especial de paz",
  "el silencio es oro en momentos de mucha confusion",
  "la manzana roja estaba muy dulce y sabrosa",
  "el viento sopla fuerte entre las ramas de los pinos",
  "la tecnologia cambia el mundo a una velocidad asombrosa",
  "escribir rapido requiere practica y mucha concentracion",
  "el teclado mecanico hace un ruido muy satisfactorio",
  "los sueños se cumplen con esfuerzo y dedicacion diaria",
  "la libertad es el tesoro mas preciado del ser humano",
  "el perro corre tras la pelota en el parque grande",
  "comer frutas y verduras es esencial para vivir bien",
  "la luna llena ilumina el camino de los viajeros",
  "un buen libro es un compañero fiel para siempre",
  "la humildad nos hace grandes ante los ojos del mundo",
  "el esfuerzo constante siempre da sus frutos al final",
  "la mente es un musculo que debemos ejercitar siempre",
  "el cielo azul invita a salir a pasear un rato",
  "la verdad siempre encuentra su camino hacia la luz",
  "un cafe amargo sabe mejor con un buen libro",
  "la programacion es el lenguaje del futuro cercano",
  "los pajaros cantan al amanecer en mi ventana",
  "el invierno trae nieve y frio a las montañas",
  "la valentia no es la ausencia de miedo sino actuar",
  "una dieta equilibrada ayuda a mantener la energia alta",
  "la gratitud transforma lo que tenemos en suficiente",
  "el arte de escuchar es tan importante como hablar",
  "la ciudad nunca duerme bajo las luces de neon",
  "un abrazo sincero vale mas que mil regalos caros",
  "la naturaleza nos enseña lecciones de supervivencia",
  "el camino mas largo empieza con un simple paso",
  "la mente creativa no conoce limites ni fronteras",
  "el respeto es la base de cualquier relacion humana",
  "la honestidad es un valor que nunca pasa de moda",
  "el trabajo en equipo logra cosas increibles siempre",
  "la pasion por lo que haces se nota en el resultado",
  "el mar en calma refleja el azul del cielo infinito",
  "la musica de fondo ayuda a concentrarse al trabajar",
  "un dia sin reir es un dia perdido para siempre",
  "la disciplina vence al talento cuando este no se esfuerza",
  "el amanecer en la playa es un espectaculo unico",
  "la sombra de los arboles refresca el verano calido",
  "un pequeño detalle puede hacer una gran diferencia",
  "la constancia es el secreto de los grandes logros",
  "el chocolate negro es mi debilidad en las tardes",
  "la lluvia golpea los cristales con un ritmo suave",
  "un buen descanso es clave para rendir al maximo",
  "la imaginacion es el principio de la creacion",
  "el orden en el escritorio ayuda al orden mental",
  "la vida es corta para aprender todos los lenguajes",
  "el bosque escondia secretos que nadie conocia aun",
  "la luz del faro guia a los barcos en la tormenta",
  "un mapa viejo mostraba el camino al tesoro oculto",
  "la arena fina se escapa entre los dedos de la mano",
  "el aroma del pan recien hecho inunda la casa",
  "la sencillez es la clave de la elegancia verdadera",
  "un secreto guardado bajo llave en el viejo baul",
  "la danza de las hojas secas en el otoño dorado",
  "el brillo de los ojos delata una gran emocion",
  "la palabra dicha no puede volver atras nunca",
  "un puente de piedra cruza el rio caudaloso",
  "la huella en la nieve desaparece con el viento",
  "el sabor de la victoria es dulce tras el esfuerzo",
  "la mirada perdida en el horizonte lejano y gris",
  "un poema escrito en una servilleta de papel",
  "la fuerza de voluntad mueve montañas muy altas",
  "el sonido de las olas rompiendo en las rocas",
  "una meta sin un plan es solo un deseo lejano",
  "la chispa de una idea puede encender un bosque",
  "el final de este camino es el inicio de otro"
];